baseURL = "https://buta7.netlify.app/"
languageCode = "en-us"
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = "Nagoya Second Line"
theme = "dream"
#theme = "dream-plus"
dateFormat = "Monday, Jan 2, 2006"
copyright = "@buta7.com"

paginate = 12

googleAnalytics = "UA-171511257-1"
disqusShortname = "buta7-netlify-app"
# enableRobotsTXT = true

[taxonomies]
  categories = "categories"
  tags = "tags"
  artists = "artists"

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "orangered"

  author = "higebobo"
  description = ""
  #avatar = "/img/avatar.jpg"
  avatar = "/images/sillywalk.png"
  motto = "The Ministry of Silly Walks"

  twitter = "higebobo"
  github = "buta7"
  #gitlab = "buta7"
  #bitbucket = "bitbucket"

  siteStartYear = 2004

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "orange"
  darkNav = true
  dark404Button = true

[languages]
  [languages.ja]
  title = "名古屋セカンドライン・わっしょい"
  dateFormat = "2006年1月2日"
