baseURL = "https://buta7.netlify.app/"
languageCode = "en-us"
defaultContentLanguage = "ja"
title = "Music Buta7"
theme = "dream"

copyright = "buta7@com"

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "buta7"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "Get the blues away"

  #email = "g1enyy0ung@gmail.com"
  github = "https://github.com/buta7"
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true
