baseURL = "https://buta7.netlify.app/"
languageCode = "en-us"
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = "Nagoya Second Line"
theme = "dream"
dateFormat = "Monday, Jan 2, 2006"
copyright = "@buta7.com"

googleAnalytics = "UA-171511257-1"
disqusShortname = "buta7-netlify-app"
# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "higebobo"
  description = ""
  #avatar = "/img/avatar.jpg"
  avatar = "/images/sillywalk.png"
  motto = "The Ministry of Silly Walks"

  #email = "g1enyy0ung@gmail.com"
  twitter = "higebobo"
  github = "buta7"
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2004

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true

[languages]
  [languages.ja]
  title = "名古屋セカンドライン・わっしょい"
  dateFormat = "2006年1月2日"